/* eslint react/prop-types: 0 */
import React from 'react';
import PropTypes from 'prop-types';
import fetch from 'node-fetch';
import ReactHighcharts from 'react-highcharts';

// import HighchartsMore from 'highcharts-more';
// HighchartsMore(ReactHighcharts.Highcharts);

class AMASSJobByUserChart extends React.Component {
  static propTypes = {
    sys: PropTypes.string.isRequired,
    charts: PropTypes.array.isRequired,
  };
  constructor(props) {
    super(props);

    if (props.sys === 'cipres') {
      this.state = {
        posts: [
          ['000generic', 57],
          ['5887pintob', 97],
          ['Abigailc', 142],
          ['AlanMarron', 65],
          ['Alisha10', 54],
          ['AndreasFroebius', 54],
          ['Andz', 70],
          ['AnushaE', 62],
          ['Athenalam', 57],
          ['BMoyersoen', 53],
          ['BayesFactor', 137],
          ['Breyta', 83],
          ['BrunnoBueno', 72],
          ['CJudith', 52],
          ['CalasLee', 64],
          ['CarlosMoura', 244],
          ['CarmenPedraza', 52],
          ['Charlie', 124],
          ['Chayanard', 59],
          ['Danushka', 75],
          ['Daotar', 62],
          ['Dennis1234', 72],
          ['Diushi', 88],
          ['EmmyvandeV', 61],
          ['Eudyptes', 105],
          ['EuvaldoJr', 56],
          ['FARIDEHMOHARREK', 74],
          ['FranciscaHervas', 239],
          ['Frexo', 70],
          ['Frisch', 84],
          ['GaikEe', 63],
          ['Gillbriana', 205],
          ['Giovanni', 83],
          ['HSuzany', 57],
          ['Hiran_Ari', 71],
          ['HsinLee2', 54],
          ['Irene', 269],
          ['JSouthworth', 110],
          ['JanHackel', 91],
          ['JoeRex40', 56],
          ['JohnP', 67],
          ['Karis', 73],
          ['Kim78', 235],
          ['KojunKanda', 74],
          ['Labisko', 85],
          ['Lactifluus', 67],
          ['LaiaLeria', 55],
          ['Lejeunea', 136],
          ['Lena23', 152],
          ['Liesbeth123', 54],
          ['Liyunyin', 87],
          ['Lopes_Filho', 190],
          ['Luciano_Palmieri', 90],
          ['LuisMachado', 165],
          ['MZsolt', 71],
          ['Magpie101', 74],
          ['Maitane2', 63],
          ['Mandyrin', 61],
          ['Manpreet', 118],
          ['ManpreetKohli', 103],
          ['MiltonTan', 118],
          ['MiselJelic', 109],
          ['Mtump', 54],
          ['Murdock', 102],
          ['NV100', 82],
          ['NerissaN', 477],
          ['PaulKirika', 241],
          ['Pepke', 72],
          ['Ponzetto', 65],
          ['Pzaharias', 85],
          ['Roland_Veggie', 51],
          ['STanaka', 61],
          ['SergeDW', 68],
          ['ShooprDoopr', 125],
          ['Sidonie', 51],
          ['Silas', 93],
          ['SiminLiu', 100],
          ['SiriusB', 76],
          ['StefanG', 56],
          ['SumanUConn', 103],
          ['Sunbingo', 66],
          ['Tabima', 76],
          ['Veenashiva216', 107],
          ['Veranso', 161],
          ['Vinicoltro', 77],
          ['Wenheng_lab', 77],
          ['XiangCL', 120],
          ['ZyangHe', 68],
          ['abufidel', 88],
          ['adeekotosin', 54],
          ['adiapeCantvNet', 164],
          ['afrotheria', 217],
          ['agolnar', 58],
          ['amacficus', 271],
          ['amvbrown', 65],
          ['anaalba', 164],
          ['andersonvieira12@iplantcollaborative.org', 68],
          ['andrew.wiewel', 111],
          ['angibeast', 56],
          ['apepato', 163],
          ['austinhpatton', 56],
          ['banxs', 197],
          ['bboyer', 63],
          ['beckpowers', 85],
          ['brunosampaio', 111],
          ['btpiatkowski', 67],
          ['bushtanager', 65],
          ['byrneh1', 56],
          ['caitlin_baker', 56],
          ['campbe28', 56],
          ['carolbioms', 52],
          ['caylward92', 66],
          ['cdiller4', 73],
          ['cdk110', 56],
          ['cdmckee', 116],
          ['cezumajo', 79],
          ['chasegator', 154],
          ['chenbiology', 210],
          ['chenjing', 78],
          ['chenxun0406', 59],
          ['chipcoi888', 197],
          ['chipcoi889', 55],
          ['cjpardo10', 77],
          ['cklinger', 145],
          ['clidemia', 68],
          ['cpraz', 59],
          ['cpvfox', 92],
          ['ctrevisan', 70],
          ['cws187', 54],
          ['dadi', 78],
          ['danielproud', 213],
          ['darrrn', 60],
          ['dfmoralesb', 152],
          ['dias', 61],
          ['diegodelagente', 53],
          ['dillmanc', 165],
          ['dnadeeshan', 52],
          ['draheem', 431],
          ['dskaltsas', 235],
          ['dstankovic', 110],
          ['duarte', 78],
          ['eapiedra', 70],
          ['ekrichil', 53],
          ['elsie', 56],
          ['emidavis', 57],
          ['erikfunk', 69],
          ['erspear', 107],
          ['eskedc', 63],
          ['evagotze', 106],
          ['fabunanr', 63],
          ['fbquinteiro', 62],
          ['fernandac1980', 55],
          ['fforest', 53],
          ['franvel', 76],
          ['fredlarabee', 56],
          ['frustulia', 97],
          ['fsantini', 76],
          ['fw1990', 140],
          ['gabicalegario', 200],
          ['garnierlucie', 91],
          ['gdnwb3', 165],
          ['genia882', 82],
          ['geoby', 55],
          ['georgievas', 65],
          ['giuliaf', 90],
          ['guidobonthond', 67],
          ['guiseger', 105],
          ['guocen', 75],
          ['guoying', 134],
          ['haronowi', 60],
          ['horka', 61],
          ['hschaefer', 51],
          ['huangchunxiu', 57],
          ['huangjie1', 54],
          ['hymeno', 53],
          ['ibaiolar', 114],
          ['icardenas', 61],
          ['igb4tonda', 90],
          ['isacan', 210],
          ['isemmour', 97],
          ['jacklongino', 107],
          ['jackscanlan', 75],
          ['jacoborv', 51],
          ['jalindo29', 87],
          ['jasone', 75],
          ['jboutagg', 57],
          ['jcgarcia', 192],
          ['jfmorales', 146],
          ['jfmsilva', 63],
          ['jgcosgrove', 67],
          ['jgillung', 53],
          ['jimcohen1000', 62],
          ['jlawrey', 125],
          ['joanne', 106],
          ['joaofungo', 63],
          ['josieneveloso@iplantcollaborative.org', 70],
          ['jrmaciel', 53],
          ['juanin', 88],
          ['justinshaffer', 83],
          ['jvarmstead', 60],
          ['jwyap1980@iplantcollaborative.org', 60],
          ['kat_sol', 62],
          ['keith.bayless', 57],
          ['kerui', 96],
          ['kimbellstone', 60],
          ['king0393', 181],
          ['kole_135', 54],
          ['kroschm', 66],
          ['kwaku', 124],
          ['kwray', 60],
          ['laosensis', 111],
          ['laura133', 52],
          ['lav', 324],
          ['lavin', 52],
          ['lchambe1', 92],
          ['lechitoan4', 64],
          ['leiyangslu', 83],
          ['lgcooper', 109],
          ['lhughes', 60],
          ['liaoyunshi', 67],
          ['lichenlab', 86],
          ['lifengyuan', 64],
          ['liujie', 78],
          ['liushihhui', 51],
          ['lixin1292006', 128],
          ['lixin1292010', 72],
          ['ljmullen2', 53],
          ['llerenard', 75],
          ['lrstreet', 56],
          ['lukesos', 53],
          ['luyongbin', 90],
          ['lwk', 54],
          ['macatanach', 63],
          ['madamverm', 64],
          ['marcusblohs', 78],
          ['marifasa', 77],
          ['mayank174', 67],
          ['mcgeematthew', 150],
          ['mcyi9ja5', 71],
          ['mellersgj', 60],
          ['mfdevecchi', 127],
          ['mfmazuecos', 120],
          ['mgoliver', 65],
          ['mhopken1', 54],
          ['mikhailchavis', 94],
          ['mjandersen', 79],
          ['mjohnso8', 213],
          ['mmpelias1983', 58],
          ['mpnelsen', 66],
          ['mrj34', 61],
          ['mucioGraf', 151],
          ['mwhahn', 66],
          ['nallarett', 65],
          ['natalyquiroz', 93],
          ['ndiver', 272],
          ['ndowie', 104],
          ['nextord', 198],
          ['niun', 82],
          ['nkandel', 123],
          ['nsupham', 208],
          ['olivertallowin', 107],
          ['omegadan01', 79],
          ['onaalvarez', 55],
          ['onenne', 70],
          ['onmikula', 75],
          ['ouliais', 236],
          ['ounap', 92],
          ['pagameangs', 56],
          ['panek3', 80],
          ['pauloliver', 51],
          ['pbauknecht', 59],
          ['peperkat', 70],
          ['qbafort', 104],
          ['raphaelorelisribeiro', 129],
          ['reason', 58],
          ['rhynchocalamus', 150],
          ['rladbgus', 93],
          ['ronaldmclouse', 124],
          ['roxisteele', 71],
          ['rstlaurent', 55],
          ['runlei', 108],
          ['ruyalu', 91],
          ['sadaf', 150],
          ['samanthafb', 54],
          ['samitkundu', 54],
          ['samutina', 109],
          ['saracecca', 107],
          ['saravandekerke', 88],
          ['sdallot', 184],
          ['sdnuqxj', 75],
          ['seanharrington256', 81],
          ['sgelias', 75],
          ['shangqiuju', 52],
          ['sharonjansa', 52],
          ['slbaldauf', 84],
          ['slemer', 80],
          ['smallcomb630', 56],
          ['smarbra', 51],
          ['soar89', 53],
          ['svasconcelos', 98],
          ['syhof', 105],
          ['tabsantos', 103],
          ['tarantuligia', 118],
          ['tenebrionid', 100],
          ['thomasx', 80],
          ['tiagojp', 76],
          ['tiagombm', 58],
          ['toddmclay', 100],
          ['tomsovsk', 76],
          ['trisa418156715', 73],
          ['trutina', 63],
          ['tswain', 57],
          ['tvasconcelos', 52],
          ['tytxxiaomi', 55],
          ['tytyalx', 75],
          ['uromastyx', 90],
          ['veronicah', 67],
          ['veronicathode', 262],
          ['vnmngan', 55],
          ['vtagliacollo', 170],
          ['wangjuan14', 55],
          ['weihan', 122],
          ['weixl', 100],
          ['willjd', 83],
          ['willkuhn', 54],
          ['xingruialex', 63],
          ['xiongyanshi', 100],
          ['yaogang1029', 53],
          ['yexiaying', 95],
          ['ylor', 117],
          ['yugh', 90],
          ['yuxiangqin', 103],
          ['zine', 76],
          ['zpopkinh', 53],
          ['zss', 67],
        ],
      };
    } else {
      this.state = {
        posts: [
          ['aseidenstein', 646],
          ['bluebirdflies', 617],
          ['bohan', 43],
          ['danielabianchi12', 37],
          ['emiliocartoni', 26],
          ['kun.tian', 84],
          ['maria.kesa', 11],
          ['mbezaire', 29],
          ['muellerleile', 208],
          ['npelot', 249],
          ['radoncBTU', 239],
          ['rjjarvis', 23],
          ['rkpowers', 14],
          ['subha', 21],
          ['wvangeit', 13],
          ['yan1982', 258],
        ],
      };
    }

    this.props.charts.push(this);
  }

  componentDidMount() {
    const that = this;
    fetch(`http://localhost:3000/amass/job/${that.props.sys}/count_by_user`)
      .then(res => res.text())
      .then(body => that.setState({ posts: JSON.parse(body) }));
  }

  render() {
    const categories = [];
    const values = [];
    let maxValue = 0;
    for (let i = 0; i < this.state.posts.length; i += 1) {
      categories.push(this.state.posts[i][0]);
      values.push(this.state.posts[i][1]);
      maxValue = Math.max(maxValue, this.state.posts[i][1]);
    }

    const config = {
      chart: {
        type: 'column',
        width: Math.max(categories.length * 20, 500),
      },
      title: {
        text: `Jobs by Users for ${this.props.sys.toUpperCase()}`,
        align: 'left',
        x: categories.length * 20 > 500 ? 450 : 150,
        style: {
          fontFamily: 'sans-serif',
          fontSize: '12pt',
          fontWeight: 'normal',
          color: 'black',
        },
      },
      legend: {
        enabled: false,
      },
      xAxis: {
        categories,
        crosshair: true,
        labels: {
          rotation: -45,
          style: {
            fontWeight: 'normal',
            color: 'darkgreen',
          },
        },
      },
      yAxis: {
        min: 0,
        max: maxValue,
        title: {
          text: 'Number of Jobs',
        },
        labels: {
          rotation: 0,
          style: {
            fontWeight: 'normal',
            color: 'darkgreen',
          },
        },
        tickInterval: 100,
      },
      /*
      tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat:
          '<tr><td style="color:{series.color};padding:0">{series.name}: </td>'+
          '<td style="padding:0"><b>{point.y:.0f}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true,
      },
      */
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0,
        },
      },
      series: [
        {
          name: 'Jobs',
          data: values,
        },
      ],
    };

    return React.createElement(ReactHighcharts, { config });
  }
}

export default AMASSJobByUserChart;
