/* eslint react/prop-types: 0 */
import React from 'react';
import PropTypes from 'prop-types';
import fetch from 'node-fetch';
import ReactHighcharts from 'react-highcharts';

class AMASSJobFractionByResourceChart extends React.Component {
  static propTypes = {
    sys: PropTypes.string.isRequired,
    charts: PropTypes.array.isRequired,
  };

  constructor(props) {
    super(props);

    if (props.sys === 'cipres') {
      this.state = {
        posts: [
          ['000generic', 0, 0],
          ['000generic', 1, 57],
          ['5887pintob', 0, 7],
          ['5887pintob', 1, 90],
          ['Abigailc', 0, 19],
          ['Abigailc', 1, 123],
          ['abufidel', 0, 3],
          ['abufidel', 1, 85],
          ['adeekotosin', 0, 0],
          ['adeekotosin', 1, 54],
          ['adiapeCantvNet', 0, 15],
          ['adiapeCantvNet', 1, 149],
          ['afrotheria', 0, 12],
          ['afrotheria', 1, 205],
          ['agolnar', 0, 3],
          ['agolnar', 1, 55],
          ['AlanMarron', 0, 2],
          ['AlanMarron', 1, 63],
          ['Alisha10', 0, 4],
          ['Alisha10', 1, 50],
          ['amacficus', 0, 18],
          ['amacficus', 1, 253],
          ['amvbrown', 0, 4],
          ['amvbrown', 1, 61],
          ['anaalba', 0, 7],
          ['anaalba', 1, 157],
          ['andersonvieira12@iplantcollaborative.org', 0, 1],
          ['andersonvieira12@iplantcollaborative.org', 1, 67],
          ['AndreasFroebius', 0, 5],
          ['AndreasFroebius', 1, 49],
          ['andrew.wiewel', 0, 15],
          ['andrew.wiewel', 1, 96],
          ['Andz', 0, 21],
          ['Andz', 1, 49],
          ['angibeast', 0, 4],
          ['angibeast', 1, 52],
          ['AnushaE', 0, 0],
          ['AnushaE', 1, 62],
          ['apepato', 0, 35],
          ['apepato', 1, 128],
          ['Athenalam', 0, 4],
          ['Athenalam', 1, 53],
          ['austinhpatton', 0, 4],
          ['austinhpatton', 1, 52],
          ['banxs', 0, 18],
          ['banxs', 1, 179],
          ['BayesFactor', 0, 15],
          ['BayesFactor', 1, 122],
          ['bboyer', 0, 1],
          ['bboyer', 1, 62],
          ['beckpowers', 0, 4],
          ['beckpowers', 1, 81],
          ['BMoyersoen', 0, 0],
          ['BMoyersoen', 1, 53],
          ['Breyta', 0, 1],
          ['Breyta', 1, 82],
          ['BrunnoBueno', 0, 14],
          ['BrunnoBueno', 1, 58],
          ['brunosampaio', 0, 0],
          ['brunosampaio', 1, 111],
          ['btpiatkowski', 0, 1],
          ['btpiatkowski', 1, 66],
          ['bushtanager', 0, 0],
          ['bushtanager', 1, 65],
          ['byrneh1', 0, 17],
          ['byrneh1', 1, 39],
          ['caitlin_baker', 0, 2],
          ['caitlin_baker', 1, 54],
          ['CalasLee', 0, 19],
          ['CalasLee', 1, 45],
          ['campbe28', 0, 8],
          ['campbe28', 1, 48],
          ['CarlosMoura', 0, 30],
          ['CarlosMoura', 1, 214],
          ['CarmenPedraza', 0, 2],
          ['CarmenPedraza', 1, 50],
          ['carolbioms', 0, 5],
          ['carolbioms', 1, 47],
          ['caylward92', 0, 3],
          ['caylward92', 1, 63],
          ['cdiller4', 0, 3],
          ['cdiller4', 1, 70],
          ['cdk110', 0, 1],
          ['cdk110', 1, 55],
          ['cdmckee', 0, 15],
          ['cdmckee', 1, 101],
          ['cezumajo', 0, 7],
          ['cezumajo', 1, 72],
          ['Charlie', 0, 6],
          ['Charlie', 1, 118],
          ['chasegator', 0, 18],
          ['chasegator', 1, 136],
          ['Chayanard', 0, 3],
          ['Chayanard', 1, 56],
          ['chenbiology', 0, 38],
          ['chenbiology', 1, 172],
          ['chenjing', 0, 3],
          ['chenjing', 1, 75],
          ['chenxun0406', 0, 12],
          ['chenxun0406', 1, 47],
          ['chipcoi888', 0, 17],
          ['chipcoi888', 1, 180],
          ['chipcoi889', 0, 2],
          ['chipcoi889', 1, 53],
          ['cjpardo10', 0, 3],
          ['cjpardo10', 1, 74],
          ['CJudith', 0, 6],
          ['CJudith', 1, 46],
          ['cklinger', 0, 10],
          ['cklinger', 1, 135],
          ['clidemia', 0, 7],
          ['clidemia', 1, 61],
          ['cpraz', 0, 1],
          ['cpraz', 1, 58],
          ['cpvfox', 0, 42],
          ['cpvfox', 1, 50],
          ['ctrevisan', 0, 2],
          ['ctrevisan', 1, 68],
          ['cws187', 0, 7],
          ['cws187', 1, 47],
          ['dadi', 0, 0],
          ['dadi', 1, 78],
          ['danielproud', 0, 14],
          ['danielproud', 1, 199],
          ['Danushka', 0, 0],
          ['Danushka', 1, 75],
          ['Daotar', 0, 0],
          ['Daotar', 1, 62],
          ['darrrn', 0, 2],
          ['darrrn', 1, 58],
          ['Dennis1234', 0, 7],
          ['Dennis1234', 1, 65],
          ['dfmoralesb', 0, 56],
          ['dfmoralesb', 1, 96],
          ['dias', 0, 1],
          ['dias', 1, 60],
          ['diegodelagente', 0, 0],
          ['diegodelagente', 1, 53],
          ['dillmanc', 0, 8],
          ['dillmanc', 1, 157],
          ['Diushi', 0, 17],
          ['Diushi', 1, 71],
          ['dnadeeshan', 0, 3],
          ['dnadeeshan', 1, 49],
          ['draheem', 0, 13],
          ['draheem', 1, 418],
          ['dskaltsas', 0, 11],
          ['dskaltsas', 1, 224],
          ['dstankovic', 0, 15],
          ['dstankovic', 1, 95],
          ['duarte', 0, 6],
          ['duarte', 1, 72],
          ['eapiedra', 0, 0],
          ['eapiedra', 1, 70],
          ['ekrichil', 0, 0],
          ['ekrichil', 1, 53],
          ['elsie', 0, 2],
          ['elsie', 1, 54],
          ['emidavis', 0, 0],
          ['emidavis', 1, 57],
          ['EmmyvandeV', 0, 7],
          ['EmmyvandeV', 1, 54],
          ['erikfunk', 0, 2],
          ['erikfunk', 1, 67],
          ['erspear', 0, 1],
          ['erspear', 1, 106],
          ['eskedc', 0, 8],
          ['eskedc', 1, 55],
          ['Eudyptes', 0, 3],
          ['Eudyptes', 1, 102],
          ['EuvaldoJr', 0, 0],
          ['EuvaldoJr', 1, 56],
          ['evagotze', 0, 1],
          ['evagotze', 1, 105],
          ['fabunanr', 0, 4],
          ['fabunanr', 1, 59],
          ['FARIDEHMOHARREK', 0, 9],
          ['FARIDEHMOHARREK', 1, 65],
          ['fbquinteiro', 0, 1],
          ['fbquinteiro', 1, 61],
          ['fernandac1980', 0, 4],
          ['fernandac1980', 1, 51],
          ['fforest', 0, 27],
          ['fforest', 1, 26],
          ['FranciscaHervas', 0, 19],
          ['FranciscaHervas', 1, 220],
          ['franvel', 0, 7],
          ['franvel', 1, 69],
          ['fredlarabee', 0, 14],
          ['fredlarabee', 1, 42],
          ['Frexo', 0, 1],
          ['Frexo', 1, 69],
          ['Frisch', 0, 0],
          ['Frisch', 1, 84],
          ['frustulia', 0, 2],
          ['frustulia', 1, 95],
          ['fsantini', 0, 2],
          ['fsantini', 1, 74],
          ['fw1990', 0, 6],
          ['fw1990', 1, 134],
          ['gabicalegario', 0, 0],
          ['gabicalegario', 1, 200],
          ['GaikEe', 0, 2],
          ['GaikEe', 1, 61],
          ['garnierlucie', 0, 6],
          ['garnierlucie', 1, 85],
          ['gdnwb3', 0, 6],
          ['gdnwb3', 1, 159],
          ['genia882', 0, 7],
          ['genia882', 1, 75],
          ['geoby', 0, 1],
          ['geoby', 1, 54],
          ['georgievas', 0, 0],
          ['georgievas', 1, 65],
          ['Gillbriana', 0, 19],
          ['Gillbriana', 1, 186],
          ['Giovanni', 0, 4],
          ['Giovanni', 1, 79],
          ['giuliaf', 0, 1],
          ['giuliaf', 1, 89],
          ['guidobonthond', 0, 4],
          ['guidobonthond', 1, 63],
          ['guiseger', 0, 0],
          ['guiseger', 1, 105],
          ['guocen', 0, 3],
          ['guocen', 1, 72],
          ['guoying', 0, 10],
          ['guoying', 1, 124],
          ['haronowi', 0, 1],
          ['haronowi', 1, 59],
          ['Hiran_Ari', 0, 3],
          ['Hiran_Ari', 1, 68],
          ['horka', 0, 8],
          ['horka', 1, 53],
          ['hschaefer', 0, 0],
          ['hschaefer', 1, 51],
          ['HsinLee2', 0, 17],
          ['HsinLee2', 1, 37],
          ['HSuzany', 0, 0],
          ['HSuzany', 1, 57],
          ['huangchunxiu', 0, 0],
          ['huangchunxiu', 1, 57],
          ['huangjie1', 0, 1],
          ['huangjie1', 1, 53],
          ['hymeno', 0, 11],
          ['hymeno', 1, 42],
          ['ibaiolar', 0, 9],
          ['ibaiolar', 1, 105],
          ['icardenas', 0, 2],
          ['icardenas', 1, 59],
          ['igb4tonda', 0, 4],
          ['igb4tonda', 1, 86],
          ['Irene', 0, 9],
          ['Irene', 1, 260],
          ['isacan', 0, 20],
          ['isacan', 1, 190],
          ['isemmour', 0, 12],
          ['isemmour', 1, 85],
          ['jacklongino', 0, 25],
          ['jacklongino', 1, 82],
          ['jackscanlan', 0, 1],
          ['jackscanlan', 1, 74],
          ['jacoborv', 0, 6],
          ['jacoborv', 1, 45],
          ['jalindo29', 0, 4],
          ['jalindo29', 1, 83],
          ['JanHackel', 0, 5],
          ['JanHackel', 1, 86],
          ['jasone', 0, 0],
          ['jasone', 1, 75],
          ['jboutagg', 0, 3],
          ['jboutagg', 1, 54],
          ['jcgarcia', 0, 13],
          ['jcgarcia', 1, 179],
          ['jfmorales', 0, 9],
          ['jfmorales', 1, 137],
          ['jfmsilva', 0, 3],
          ['jfmsilva', 1, 60],
          ['jgcosgrove', 0, 4],
          ['jgcosgrove', 1, 63],
          ['jgillung', 0, 3],
          ['jgillung', 1, 50],
          ['jimcohen1000', 0, 2],
          ['jimcohen1000', 1, 60],
          ['jlawrey', 0, 1],
          ['jlawrey', 1, 124],
          ['joanne', 0, 2],
          ['joanne', 1, 104],
          ['joaofungo', 0, 5],
          ['joaofungo', 1, 58],
          ['JoeRex40', 0, 0],
          ['JoeRex40', 1, 56],
          ['JohnP', 0, 10],
          ['JohnP', 1, 57],
          ['josieneveloso@iplantcollaborative.org', 0, 4],
          ['josieneveloso@iplantcollaborative.org', 1, 66],
          ['jrmaciel', 0, 11],
          ['jrmaciel', 1, 42],
          ['JSouthworth', 0, 12],
          ['JSouthworth', 1, 98],
          ['juanin', 0, 6],
          ['juanin', 1, 82],
          ['justinshaffer', 0, 2],
          ['justinshaffer', 1, 81],
          ['jvarmstead', 0, 6],
          ['jvarmstead', 1, 54],
          ['jwyap1980@iplantcollaborative.org', 0, 8],
          ['jwyap1980@iplantcollaborative.org', 1, 52],
          ['Karis', 0, 1],
          ['Karis', 1, 72],
          ['kat_sol', 0, 3],
          ['kat_sol', 1, 59],
          ['keith.bayless', 0, 0],
          ['keith.bayless', 1, 57],
          ['kerui', 0, 19],
          ['kerui', 1, 77],
          ['Kim78', 0, 9],
          ['Kim78', 1, 226],
          ['kimbellstone', 0, 3],
          ['kimbellstone', 1, 57],
          ['king0393', 0, 13],
          ['king0393', 1, 168],
          ['KojunKanda', 0, 17],
          ['KojunKanda', 1, 57],
          ['kole_135', 0, 2],
          ['kole_135', 1, 52],
          ['kroschm', 0, 5],
          ['kroschm', 1, 61],
          ['kwaku', 0, 2],
          ['kwaku', 1, 122],
          ['kwray', 0, 3],
          ['kwray', 1, 57],
          ['Labisko', 0, 9],
          ['Labisko', 1, 76],
          ['Lactifluus', 0, 18],
          ['Lactifluus', 1, 49],
          ['LaiaLeria', 0, 1],
          ['LaiaLeria', 1, 54],
          ['laosensis', 0, 3],
          ['laosensis', 1, 108],
          ['laura133', 0, 0],
          ['laura133', 1, 52],
          ['lav', 0, 21],
          ['lav', 1, 303],
          ['lavin', 0, 1],
          ['lavin', 1, 51],
          ['lchambe1', 0, 0],
          ['lchambe1', 1, 92],
          ['lechitoan4', 0, 1],
          ['lechitoan4', 1, 63],
          ['leiyangslu', 0, 36],
          ['leiyangslu', 1, 47],
          ['Lejeunea', 0, 5],
          ['Lejeunea', 1, 131],
          ['Lena23', 0, 1],
          ['Lena23', 1, 151],
          ['lgcooper', 0, 10],
          ['lgcooper', 1, 99],
          ['lhughes', 0, 2],
          ['lhughes', 1, 58],
          ['liaoyunshi', 0, 1],
          ['liaoyunshi', 1, 66],
          ['lichenlab', 0, 3],
          ['lichenlab', 1, 83],
          ['Liesbeth123', 0, 6],
          ['Liesbeth123', 1, 48],
          ['lifengyuan', 0, 3],
          ['lifengyuan', 1, 61],
          ['liujie', 0, 2],
          ['liujie', 1, 76],
          ['liushihhui', 0, 0],
          ['liushihhui', 1, 51],
          ['lixin1292006', 0, 4],
          ['lixin1292006', 1, 124],
          ['lixin1292010', 0, 9],
          ['lixin1292010', 1, 63],
          ['Liyunyin', 0, 7],
          ['Liyunyin', 1, 80],
          ['ljmullen2', 0, 1],
          ['ljmullen2', 1, 52],
          ['llerenard', 0, 0],
          ['llerenard', 1, 75],
          ['Lopes_Filho', 0, 3],
          ['Lopes_Filho', 1, 187],
          ['lrstreet', 0, 3],
          ['lrstreet', 1, 53],
          ['Luciano_Palmieri', 0, 0],
          ['Luciano_Palmieri', 1, 90],
          ['LuisMachado', 0, 8],
          ['LuisMachado', 1, 157],
          ['lukesos', 0, 3],
          ['lukesos', 1, 50],
          ['luyongbin', 0, 2],
          ['luyongbin', 1, 88],
          ['lwk', 0, 0],
          ['lwk', 1, 54],
          ['macatanach', 0, 0],
          ['macatanach', 1, 63],
          ['madamverm', 0, 2],
          ['madamverm', 1, 62],
          ['Magpie101', 0, 1],
          ['Magpie101', 1, 73],
          ['Maitane2', 0, 7],
          ['Maitane2', 1, 56],
          ['Mandyrin', 0, 3],
          ['Mandyrin', 1, 58],
          ['Manpreet', 0, 6],
          ['Manpreet', 1, 112],
          ['ManpreetKohli', 0, 0],
          ['ManpreetKohli', 1, 103],
          ['marcusblohs', 0, 8],
          ['marcusblohs', 1, 70],
          ['marifasa', 0, 1],
          ['marifasa', 1, 76],
          ['mayank174', 0, 0],
          ['mayank174', 1, 67],
          ['mcgeematthew', 0, 4],
          ['mcgeematthew', 1, 146],
          ['mcyi9ja5', 0, 2],
          ['mcyi9ja5', 1, 69],
          ['mellersgj', 0, 4],
          ['mellersgj', 1, 56],
          ['mfdevecchi', 0, 0],
          ['mfdevecchi', 1, 127],
          ['mfmazuecos', 0, 12],
          ['mfmazuecos', 1, 108],
          ['mgoliver', 0, 4],
          ['mgoliver', 1, 61],
          ['mhopken1', 0, 2],
          ['mhopken1', 1, 52],
          ['mikhailchavis', 0, 7],
          ['mikhailchavis', 1, 87],
          ['MiltonTan', 0, 8],
          ['MiltonTan', 1, 110],
          ['MiselJelic', 0, 5],
          ['MiselJelic', 1, 104],
          ['mjandersen', 0, 8],
          ['mjandersen', 1, 71],
          ['mjohnso8', 0, 15],
          ['mjohnso8', 1, 198],
          ['mmpelias1983', 0, 6],
          ['mmpelias1983', 1, 52],
          ['mpnelsen', 0, 8],
          ['mpnelsen', 1, 58],
          ['mrj34', 0, 3],
          ['mrj34', 1, 58],
          ['Mtump', 0, 6],
          ['Mtump', 1, 48],
          ['mucioGraf', 0, 22],
          ['mucioGraf', 1, 129],
          ['Murdock', 0, 8],
          ['Murdock', 1, 94],
          ['mwhahn', 0, 1],
          ['mwhahn', 1, 65],
          ['MZsolt', 0, 0],
          ['MZsolt', 1, 71],
          ['nallarett', 0, 0],
          ['nallarett', 1, 65],
          ['natalyquiroz', 0, 7],
          ['natalyquiroz', 1, 86],
          ['ndiver', 0, 4],
          ['ndiver', 1, 268],
          ['ndowie', 0, 4],
          ['ndowie', 1, 100],
          ['NerissaN', 0, 8],
          ['NerissaN', 1, 469],
          ['nextord', 0, 1],
          ['nextord', 1, 197],
          ['niun', 0, 5],
          ['niun', 1, 77],
          ['nkandel', 0, 2],
          ['nkandel', 1, 121],
          ['nsupham', 0, 22],
          ['nsupham', 1, 186],
          ['NV100', 0, 2],
          ['NV100', 1, 80],
          ['olivertallowin', 0, 8],
          ['olivertallowin', 1, 99],
          ['omegadan01', 0, 2],
          ['omegadan01', 1, 77],
          ['onaalvarez', 0, 4],
          ['onaalvarez', 1, 51],
          ['onenne', 0, 3],
          ['onenne', 1, 67],
          ['onmikula', 0, 7],
          ['onmikula', 1, 68],
          ['ouliais', 0, 15],
          ['ouliais', 1, 221],
          ['ounap', 0, 7],
          ['ounap', 1, 85],
          ['pagameangs', 0, 4],
          ['pagameangs', 1, 52],
          ['panek3', 0, 1],
          ['panek3', 1, 79],
          ['PaulKirika', 0, 0],
          ['PaulKirika', 1, 241],
          ['pauloliver', 0, 6],
          ['pauloliver', 1, 45],
          ['pbauknecht', 0, 0],
          ['pbauknecht', 1, 59],
          ['peperkat', 0, 31],
          ['peperkat', 1, 39],
          ['Pepke', 0, 14],
          ['Pepke', 1, 58],
          ['Ponzetto', 0, 2],
          ['Ponzetto', 1, 63],
          ['Pzaharias', 0, 12],
          ['Pzaharias', 1, 73],
          ['qbafort', 0, 11],
          ['qbafort', 1, 93],
          ['raphaelorelisribeiro', 0, 7],
          ['raphaelorelisribeiro', 1, 122],
          ['reason', 0, 8],
          ['reason', 1, 50],
          ['rhynchocalamus', 0, 5],
          ['rhynchocalamus', 1, 145],
          ['rladbgus', 0, 4],
          ['rladbgus', 1, 89],
          ['Roland_Veggie', 0, 5],
          ['Roland_Veggie', 1, 46],
          ['ronaldmclouse', 0, 30],
          ['ronaldmclouse', 1, 94],
          ['roxisteele', 0, 15],
          ['roxisteele', 1, 56],
          ['rstlaurent', 0, 10],
          ['rstlaurent', 1, 45],
          ['runlei', 0, 1],
          ['runlei', 1, 107],
          ['ruyalu', 0, 5],
          ['ruyalu', 1, 86],
          ['sadaf', 0, 2],
          ['sadaf', 1, 148],
          ['samanthafb', 0, 0],
          ['samanthafb', 1, 54],
          ['samitkundu', 0, 0],
          ['samitkundu', 1, 54],
          ['samutina', 0, 1],
          ['samutina', 1, 108],
          ['saracecca', 0, 5],
          ['saracecca', 1, 102],
          ['saravandekerke', 0, 0],
          ['saravandekerke', 1, 88],
          ['sdallot', 0, 19],
          ['sdallot', 1, 165],
          ['sdnuqxj', 0, 4],
          ['sdnuqxj', 1, 71],
          ['seanharrington256', 0, 7],
          ['seanharrington256', 1, 74],
          ['SergeDW', 0, 0],
          ['SergeDW', 1, 68],
          ['sgelias', 0, 13],
          ['sgelias', 1, 62],
          ['shangqiuju', 0, 1],
          ['shangqiuju', 1, 51],
          ['sharonjansa', 0, 10],
          ['sharonjansa', 1, 42],
          ['ShooprDoopr', 0, 2],
          ['ShooprDoopr', 1, 123],
          ['Sidonie', 0, 1],
          ['Sidonie', 1, 50],
          ['Silas', 0, 7],
          ['Silas', 1, 86],
          ['SiminLiu', 0, 8],
          ['SiminLiu', 1, 92],
          ['SiriusB', 0, 9],
          ['SiriusB', 1, 67],
          ['slbaldauf', 0, 2],
          ['slbaldauf', 1, 82],
          ['slemer', 0, 5],
          ['slemer', 1, 75],
          ['smallcomb630', 0, 2],
          ['smallcomb630', 1, 54],
          ['smarbra', 0, 7],
          ['smarbra', 1, 44],
          ['soar89', 0, 5],
          ['soar89', 1, 48],
          ['STanaka', 0, 1],
          ['STanaka', 1, 60],
          ['StefanG', 0, 0],
          ['StefanG', 1, 56],
          ['SumanUConn', 0, 20],
          ['SumanUConn', 1, 83],
          ['Sunbingo', 0, 5],
          ['Sunbingo', 1, 61],
          ['svasconcelos', 0, 1],
          ['svasconcelos', 1, 97],
          ['syhof', 0, 7],
          ['syhof', 1, 98],
          ['Tabima', 0, 10],
          ['Tabima', 1, 66],
          ['tabsantos', 0, 12],
          ['tabsantos', 1, 91],
          ['tarantuligia', 0, 26],
          ['tarantuligia', 1, 92],
          ['tenebrionid', 0, 1],
          ['tenebrionid', 1, 99],
          ['thomasx', 0, 6],
          ['thomasx', 1, 74],
          ['tiagojp', 0, 3],
          ['tiagojp', 1, 73],
          ['tiagombm', 0, 13],
          ['tiagombm', 1, 45],
          ['toddmclay', 0, 3],
          ['toddmclay', 1, 97],
          ['tomsovsk', 0, 3],
          ['tomsovsk', 1, 73],
          ['trisa418156715', 0, 17],
          ['trisa418156715', 1, 56],
          ['trutina', 0, 0],
          ['trutina', 1, 63],
          ['tswain', 0, 1],
          ['tswain', 1, 56],
          ['tvasconcelos', 0, 2],
          ['tvasconcelos', 1, 50],
          ['tytxxiaomi', 0, 12],
          ['tytxxiaomi', 1, 43],
          ['tytyalx', 0, 1],
          ['tytyalx', 1, 74],
          ['uromastyx', 0, 23],
          ['uromastyx', 1, 67],
          ['Veenashiva216', 0, 15],
          ['Veenashiva216', 1, 92],
          ['Veranso', 0, 18],
          ['Veranso', 1, 143],
          ['veronicah', 0, 6],
          ['veronicah', 1, 61],
          ['veronicathode', 0, 0],
          ['veronicathode', 1, 262],
          ['Vinicoltro', 0, 3],
          ['Vinicoltro', 1, 74],
          ['vnmngan', 0, 9],
          ['vnmngan', 1, 46],
          ['vtagliacollo', 0, 2],
          ['vtagliacollo', 1, 168],
          ['wangjuan14', 0, 1],
          ['wangjuan14', 1, 54],
          ['weihan', 0, 7],
          ['weihan', 1, 115],
          ['weixl', 0, 7],
          ['weixl', 1, 93],
          ['Wenheng_lab', 0, 0],
          ['Wenheng_lab', 1, 77],
          ['willjd', 0, 3],
          ['willjd', 1, 80],
          ['willkuhn', 0, 0],
          ['willkuhn', 1, 54],
          ['XiangCL', 0, 2],
          ['XiangCL', 1, 118],
          ['xingruialex', 0, 1],
          ['xingruialex', 1, 62],
          ['xiongyanshi', 0, 2],
          ['xiongyanshi', 1, 98],
          ['yaogang1029', 0, 2],
          ['yaogang1029', 1, 51],
          ['yexiaying', 0, 1],
          ['yexiaying', 1, 94],
          ['ylor', 0, 7],
          ['ylor', 1, 110],
          ['yugh', 0, 4],
          ['yugh', 1, 86],
          ['yuxiangqin', 0, 6],
          ['yuxiangqin', 1, 97],
          ['zine', 0, 0],
          ['zine', 1, 76],
          ['zpopkinh', 0, 7],
          ['zpopkinh', 1, 46],
          ['zss', 0, 2],
          ['zss', 1, 65],
          ['ZyangHe', 0, 4],
          ['ZyangHe', 1, 64],
        ],
      };
    } else {
      this.state = {
        posts: [
          ['aseidenstein', 0, 156],
          ['aseidenstein', 1, 490],
          ['bluebirdflies', 0, 124],
          ['bluebirdflies', 1, 493],
          ['bohan', 0, 8],
          ['bohan', 1, 35],
          ['danielabianchi12', 0, 5],
          ['danielabianchi12', 1, 32],
          ['emiliocartoni', 0, 3],
          ['emiliocartoni', 1, 23],
          ['kun.tian', 0, 19],
          ['kun.tian', 1, 65],
          ['maria.kesa', 0, 1],
          ['maria.kesa', 1, 10],
          ['mbezaire', 0, 10],
          ['mbezaire', 1, 19],
          ['muellerleile', 0, 24],
          ['muellerleile', 1, 184],
          ['npelot', 0, 29],
          ['npelot', 1, 220],
          ['radoncBTU', 0, 8],
          ['radoncBTU', 1, 231],
          ['rjjarvis', 0, 6],
          ['rjjarvis', 1, 17],
          ['rkpowers', 0, 3],
          ['rkpowers', 1, 11],
          ['subha', 0, 9],
          ['subha', 1, 12],
          ['wvangeit', 0, 3],
          ['wvangeit', 1, 10],
          ['yan1982', 0, 35],
          ['yan1982', 1, 223],
        ],
      };
    }

    this.props.charts.push(this);
  }

  componentDidMount() {
    const that = this;
    fetch(
      `http://localhost:3000/amass/job/${that.props.sys}/finished_failed_by_user`)
      .then(res => res.text())
      .then(body => that.setState({ posts: JSON.parse(body) }));
  }

  render() {
    const categories = [];
    for (let i = 0; i < this.state.posts.length; i += 1) {
      if (!categories.includes(this.state.posts[i][0])) {
        categories.push(this.state.posts[i][0]);
      }
    }

    const failed = [];
    for (let i = 0; i < this.state.posts.length; i += 2) {
      failed.push(this.state.posts[i][2]);
    }

    const finished = [];
    for (let i = 0; i < this.state.posts.length; i += 2) {
      finished.push(this.state.posts[i + 1][2]);
    }

    const config = {
      chart: {
        type: 'column',
        width: Math.max(categories.length * 20, 500),
      },
      title: {
        text: `Finished/Failed Jobs by Users for ${this.props.sys.toUpperCase()}`,
        align: 'left',
        x: categories.length * 20 > 500 ? 370 : 120,
        style: {
          fontFamily: 'sans-serif',
          fontSize: '12pt',
          fontWeight: 'normal',
          color: 'black',
        },
      },
      xAxis: {
        categories,
        title: {
          text: 'Resources',
        },
        labels: {
          rotation: -45,
          style: {
            fontWeight: 'normal',
            color: 'darkgreen',
          },
        },
      },
      yAxis: {
        min: 0,
        title: {
          text: 'Fractions of Finished/Failed Jobs',
        },
        tickInterval: 100,
        stackLabels: {
          enabled: true,
          style: {
            fontWeight: 'normal',
            fontSize: '8pt',
            color: 'lightgrey',
          },
        },
        labels: {
          rotation: 0,
          style: {
            fontWeight: 'normal',
            color: 'darkgreen',
          },
        },
      },
      legend: {
        align: 'right',
        x: -30,
        verticalAlign: 'top',
        y: 25,
        floating: true,
        backgroundColor: 'white',
        borderColor: '#CCC',
        borderWidth: 1,
        shadow: false,
      },
      tooltip: {
        headerFormat: '<b>{point.x}</b><br/>',
        pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}',
      },
      plotOptions: {
        column: {
          stacking: 'normal',
          dataLabels: {
            enabled: false,
            color: 'white',
          },
        },
      },
      series: [
        {
          name: 'Failed',
          data: failed,
          color: 'lightgrey',
        },
        {
          name: 'Finished',
          data: finished,
        },
      ],
    };
    return React.createElement(ReactHighcharts, { config });
  }
}

export default AMASSJobFractionByResourceChart;
